apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-st
provisioner: ebs.csi.aws.com
# Below mode will not create pv even after creating pvc until some pod is associated with that pvc
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3
  fsType: ext4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
  namespace: default
spec:
  serviceName: "app"
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: persistent-storage
    spec:
      storageClassName: "ebs-st"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
