apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
# Below mode will not create pv even after creating pvc until some pod is associated with that pvc
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  fsType: ext4
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-sc-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: centos
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-sc-pvc
